apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-fulfillment
  description: the component responsible for fulfilling orders.

   


spec:
  type: service
  system: product-catalog
  lifecycle: production
  owner: team-enablement
  dependsOn:
    - resource:default/warehouse-inventory-db

  providesApis:
    - order-fulfillment-api
